name: windows-build-steps
runs:
  using: composite
  steps:
  - name: Add msbuild to PATH
    uses: microsoft/setup-msbuild@v1.3.1
  - name: Custom steps
    env:
      THIRDPARTY_HOME: ${{ github.workspace }}/thirdparty
      CMAKE_HOME: C:/Program Files/CMake
      CMAKE_BIN: C:/Program Files/CMake/bin/cmake.exe
      CTEST_BIN: C:/Program Files/CMake/bin/ctest.exe
      JAVA_HOME: C:/Program Files/BellSoft/LibericaJDK-8
      SNAPPY_HOME: ${{ github.workspace }}/thirdparty/snappy-1.1.8
      SNAPPY_INCLUDE: ${{ github.workspace }}/thirdparty/snappy-1.1.8;${{ github.workspace }}/thirdparty/snappy-1.1.8/build
      SNAPPY_LIB_DEBUG: ${{ github.workspace }}/thirdparty/snappy-1.1.8/build/Debug/snappy.lib
    run: |-
      $ErrorActionPreference = 'Stop'
      echo ===================== Install Dependencies ===================== $ErrorActionPreference
      choco install liberica8jdk -y
      mkdir $Env:THIRDPARTY_HOME
      cd $Env:THIRDPARTY_HOME
      echo "Building Snappy dependency..."
      curl -Lo snappy-1.1.8.zip https://github.com/google/snappy/archive/refs/tags/1.1.8.zip
      unzip -q snappy-1.1.8.zip
      cd snappy-1.1.8
      mkdir build
      cd build
      & cmake -G "$Env:CMAKE_GENERATOR" ..
      msbuild Not_a_solution.sln -maxCpuCount -property:Configuration=Debug -property:Platform=x64
      echo LASTEXITCODE = $LASTEXITCODE
      msbuild -help
    shell: pwsh
